In [1]:
import os
import tarfile
from six.moves import urllib

FILE_TO_DOWNLOAD =  "Salary_Data.csv"
DOWNLOAD_ROOT = "https://github.com/ect-info/ml/raw/master/"
DATA_PATH = "dados/"
DATA_URL = DOWNLOAD_ROOT + DATA_PATH + FILE_TO_DOWNLOAD

def fetch_data(data_url=DATA_URL, data_path=DATA_PATH, file_to_download=FILE_TO_DOWNLOAD):
  if not os.path.isdir(data_path):
    os.makedirs(data_path)
  urllib.request.urlretrieve(data_url, data_path+"Salary_Data.csv")
  
  
fetch_data()

# observando se o diretório datasets foi criado com sucesso 
!ls dados

Salary_Data.csv


In [17]:
import pandas as pd

def load_data(data_path=DATA_PATH, file_to_download=FILE_TO_DOWNLOAD):
  csv_path = os.path.join(data_path,file_to_download)
  return pd.read_csv(csv_path)

salary_data = load_data()

salary_data.head()


YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [18]:
# Separando os dados para a variável independente e para variável dependete 
X = salary_data.iloc[:,:-1].values
y = salary_data.iloc[:, 1].values
X

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [6]:
salary_data.describe()

YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [19]:
# Misturando os dados 

from sklearn.utils import shuffle

shuffle(salary_data)

# Separando os dados para as variáveis independentes e para variável dependete 
X = salary_data.iloc[:,:-1].values # pega todas as colunas e exclui a última
y = salary_data.iloc[:, 1].values # pega só quinta coluna 

X = X[:,[0]] # escolhendo colunas específicas de X

X_train = X[:-10]
X_test = X[-20:]

# Split the targets into training/testing sets
y_train = y[:-10]
y_test = y[-20:]

In [20]:
print(X[0:6,:])

[[1.1]
 [1.3]
 [1.5]
 [2. ]
 [2.2]
 [2.9]]


In [21]:
# Preparando para a regressão 
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(X_train, y_train)

# Make predictions using the testing set
y_pred = regr.predict(X_test)

# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean squared error
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(y_test, y_pred))

Coefficients: 
 [9116.11420069]
Mean squared error: 36655367.61
Variance score: 0.93


In [22]:
print(y_pred)
print(y_test)

[ 62130.24540221  63041.85682228  63041.85682228  63953.46824235
  67599.91392263  71246.35960291  73069.58244305  74892.80528318
  80362.4738036   81274.08522367  88566.97658422  91301.81084443
  98594.70220499 101329.53646519 105887.59356554 108622.42782575
 113180.48492609 114092.09634616 120473.37628665 122296.59912679]
[ 63218.  55794.  56957.  57081.  61111.  67938.  66029.  83088.  81363.
  93940.  91738.  98273. 101302. 113812. 109431. 105582. 116969. 112635.
 122391. 121872.]


In [15]:
y_pred

array([ 66119.45581179,  67490.14672651,  68860.83764123,  72972.91038539,
        73658.25584275,  79141.01950163,  81197.0558737 ,  86679.81953258,
        88735.85590466,  92162.58319146,  94218.61956354,  97645.34685033,
        98330.69230769, 103128.11050921, 104498.80142393])